services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: exercise-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../:/var/www

  nginx:
    image: nginx:1.19-alpine
    container_name: exercise-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d

  db:
    container_name: exercie-db
    image: mysql:8.0
    volumes:
      - ./storage/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exercise
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3308:3306